platform :ios, "8.0"

target 'QuanMinTV_iPhone' do

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.1'
pod 'Masonry', '~> 1.0.1'
pod 'BarrageRenderer', '~> 1.8.0'
pod 'LFLiveKit', '~> 1.6'
pod 'YYKit'
end
